import type { ExperimentalMaterialRecord } from "@/data/experimental-materials";

export const INITIAL_EXPERIMENTAL_MATERIALS_FIXTURE: ExperimentalMaterialRecord[] = [
  {
    id: "em-phenolphthalein-v2",
    name: "酚酞指示剂溶液",
    photoUrl: "",
    materialType: "lab_only",
    categories: ["chemistry"],
    usage: "作为酸碱指示剂，在碱性环境下由无色变粉红，用于观察酸碱变化。",
    suggestedAmount: "每组约 1 瓶（滴加 3-5 滴即可观察）",
    homeAlternative: "可用紫甘蓝浸出液替代做酸碱对比。",
    safetyTags: ["avoid_ingestion", "avoid_skin_contact"],
    safetyNote: "仅限实验，避免入口；操作后及时洗手。",
    remark: "建议避光保存，开封后尽快使用。",
    createdByActorId: "seed:teacher",
    createdAt: "2026-04-16T08:30:00.000Z",
    updatedByActorId: "seed:teacher",
    updatedAt: "2026-04-16T08:30:00.000Z",
  },
  {
    id: "em-vinegar-v2",
    name: "白醋",
    photoUrl: "",
    materialType: "home_common",
    categories: ["chemistry", "daily_supply"],
    usage: "用于家庭场景醋酸与碳酸盐反应，产生气泡/泡沫，方便学生就地取材。",
    suggestedAmount: "约 50 ml",
    homeAlternative: "可用米醋或柠檬汁替代做弱酸对比。",
    safetyTags: ["adult_supervision", "avoid_ingestion"],
    safetyNote: "需成人监督，避免溅入眼睛；不建议在实验过程中直接品尝。",
    remark: "建议搭配透明容器，便于学生观察反应现象。",
    createdByActorId: "seed:teacher",
    createdAt: "2026-04-16T08:35:00.000Z",
    updatedByActorId: "seed:teacher",
    updatedAt: "2026-04-16T08:35:00.000Z",
  },
  {
    id: "em-baking-soda-v2",
    name: "小苏打（碳酸氢钠）",
    photoUrl: "",
    materialType: "home_common",
    categories: ["chemistry", "daily_supply"],
    usage: "与醋/柠檬汁反应产生气泡，可用于观察反应快慢与配比差异。",
    suggestedAmount: "每组约 1 小包（按实验步骤分次加入）",
    homeAlternative: "可用少量泡打粉做近似对比（注意成分差异，泡沫强弱可能不同）。",
    safetyTags: ["adult_supervision", "avoid_ingestion"],
    safetyNote: "避免儿童误食；操作后洗手，实验用量以老师指导为准。",
    remark: "可配合量勺/小勺精确控制加入量。",
    createdByActorId: "seed:researcher",
    createdAt: "2026-04-16T08:40:00.000Z",
    updatedByActorId: "seed:researcher",
    updatedAt: "2026-04-16T08:40:00.000Z",
  },
  {
    id: "em-red-cabbage-v2",
    name: "紫甘蓝浸出液（天然指示剂）",
    photoUrl: "",
    materialType: "home_common",
    categories: ["biology", "chemistry"],
    usage: "作为天然酸碱指示剂，观察不同溶液颜色变化，用于实验现象记录与对比。",
    suggestedAmount: "每组约 50 ml（按步骤分次使用）",
    homeAlternative: "可用其他紫色植物提取液做对比（如紫色高丽菜萃取液）。",
    safetyTags: ["adult_supervision", "avoid_ingestion"],
    safetyNote: "建议不要直接饮用；配制与操作过程需成人监督。",
    remark: "可先在透明杯中做小样验证颜色变化是否符合预期。",
    createdByActorId: "seed:teacher",
    createdAt: "2026-04-16T08:45:00.000Z",
    updatedByActorId: "seed:teacher",
    updatedAt: "2026-04-16T08:45:00.000Z",
  },
  {
    id: "em-transparent-cup-v2",
    name: "透明一次性杯",
    photoUrl: "",
    materialType: "general",
    categories: ["general_tool", "daily_supply"],
    usage: "用于盛装反应液、便于观察颜色变化与气泡产生情况。",
    suggestedAmount: "每组 2 个（可根据步骤增减）",
    homeAlternative: "可用玻璃杯/塑料量杯替代，选择不易碎、便于观察的容器。",
    safetyTags: ["adult_supervision", "cut_protection"],
    safetyNote: "易变形或破损，轻拿轻放；破损及时更换。",
    remark: "建议搭配一次性勺或量杯以提升观察一致性。",
    createdByActorId: "seed:researcher",
    createdAt: "2026-04-16T08:50:00.000Z",
    updatedByActorId: "seed:researcher",
    updatedAt: "2026-04-16T08:50:00.000Z",
  },
];
