export const Tokens = {
  color: {
    background: "--background",
    foreground: "--foreground",
    primary: "--primary",
    primaryForeground: "--primary-foreground",
    secondary: "--secondary",
    secondaryForeground: "--secondary-foreground",
    muted: "--muted",
    mutedForeground: "--muted-foreground",
    accent: "--accent",
    accentForeground: "--accent-foreground",
    destructive: "--destructive",
    destructiveForeground: "--destructive-foreground",
    border: "--border",
    input: "--input",
    ring: "--ring",
    brandScience: "--brand-science",
    brandManagement: "--brand-management",
    statusSuccess: "--status-success",
    statusWarning: "--status-warning",
    statusError: "--status-error",
  },
  radius: {
    base: "--radius",
    sm: "--radius-sm",
    md: "--radius-md",
    lg: "--radius-lg",
    xl: "--radius-xl",
    bento: "--radius-bento",
    component: "--radius-component",
  },
} as const;

