-- ==========================================================
-- 0053: 存量 logo_url 迁移到封面子行（应用层脚本入口预留）
--
-- 由于 logo_url 存储的是完整 MinIO 公共 URL（如
-- https://minio.example.com/bslab-media/v2/user/thumb/xxx.jpg），
-- 而封面子行的 file_url 需要存储 storage key（如
-- v2/user/thumb/xxx.jpg），无法通过纯 SQL 可靠提取。
--
-- 请使用应用层迁移脚本（Deno）执行迁移：
--   deno run --allow-read --allow-env --allow-net scripts/migrate-logo-to-cover-child.ts
--
-- 应用层迁移会利用 tryStorageKeyFromFileUrl 精确提取 storage key，
-- 并支持多种 URL 格式（MinIO 直链、CDN、公网域名等）。
--
-- 迁移脚本逻辑（伪代码）：
--   1. SELECT * FROM data_file WHERE logo_url IS NOT NULL AND logo_url != ''
--      AND NOT EXISTS (SELECT 1 FROM data_file child WHERE child.parent_file_id = df.file_id AND child.relation_type = 'logo')
--   2. 对每条记录：
--      a. 调用 tryStorageKeyFromFileUrl(logo_url) 获取 storage key
--      b. 执行 INSERT INTO data_file (file_id, file_name, file_url, file_type_id, ...) VALUES (...)
--      c. 执行 UPDATE data_file SET cover_file_id = ? WHERE file_id = ?
-- ==========================================================
